import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className="font-mono">
        <main className="grid grid-cols-6">
          <Sidebar />
          <section className="col-span-6 lg:col-span-5 h-screen overflow-y-scroll">{children}</section>
        </main>
      </body>
    </html>
  );
}
