"use client";
import Overview from "@/components/Overview";
import PointRaking from "@/components/PointRaking";
import Search from "@/components/Search";
import { useEffect, useState } from "react";
import axios from "axios";
import { JsonView, darkStyles, defaultStyles } from "react-json-view-lite";
import "react-json-view-lite/dist/index.css";

export default function Home() {
  const [info, setinfo] = useState({});
  const [tt, settt] = useState([]);
  const handleGetInfo = () => {
    axios
      .get(
        "https://vn2.api.riotgames.com/lol/summoner/v4/summoners/by-name/C%C3%A1%20heo%20chin?api_key=RGAPI-2833deb2-0014-4c0d-9b04-8a0fb36905da"
      )
      .then(function (res) {
        setinfo(res);
      })
      .then((res) => {
        axios
          .get(
            "https://vn2.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-summoner/yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA/top?count=3&api_key=RGAPI-2833deb2-0014-4c0d-9b04-8a0fb36905da"
          )
          .then((res) => settt(res.data));
      })
      .catch((err) => console.log("erro"));
  };

  useEffect(() => {
    handleGetInfo();
  }, []);


  return (
    <main className="flex flex-col p-6 pb-[240px]">
      <Search />
      <h1 className="text-[24px] mt-6">Overview</h1>
      <Overview data={info.data} />
      <section className="grid grid-cols-5">
        <PointRaking data={tt} />
        <div className="col-span-5 mt-[120px]">
          <h1>20 Match</h1>
          <JsonView
            data={[
              "VN2_160213412",
              "VN2_160173930",
              "VN2_160147350",
              "VN2_160113069",
              "VN2_160051739",
              "VN2_158623155",
              "VN2_158588586",
              "VN2_158557403",
              "VN2_158535451",
              "VN2_157769474",
              "VN2_157744083",
              "VN2_157726037",
              "VN2_157671667",
              "VN2_157614844",
              "VN2_157611463",
              "VN2_156912681",
              "VN2_156873809",
              "VN2_156832737",
              "VN2_156790147",
              "VN2_156740129"
          ]}
            shouldInitiallyExpand={(level) => true}
            style={defaultStyles}
          />
                    <h1>List Champion mastery</h1>
          <JsonView
            data={[
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 157,
                  "championLevel": 7,
                  "championPoints": 350258,
                  "lastPlayTime": 1690901113000,
                  "championPointsSinceLastLevel": 328658,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 121,
                  "championLevel": 7,
                  "championPoints": 213804,
                  "lastPlayTime": 1673805921000,
                  "championPointsSinceLastLevel": 192204,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 99,
                  "championLevel": 7,
                  "championPoints": 186222,
                  "lastPlayTime": 1691169229000,
                  "championPointsSinceLastLevel": 164622,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 11,
                  "championLevel": 7,
                  "championPoints": 174777,
                  "lastPlayTime": 1689524776000,
                  "championPointsSinceLastLevel": 153177,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 81,
                  "championLevel": 7,
                  "championPoints": 156747,
                  "lastPlayTime": 1685808026000,
                  "championPointsSinceLastLevel": 135147,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 64,
                  "championLevel": 7,
                  "championPoints": 122742,
                  "lastPlayTime": 1681656739000,
                  "championPointsSinceLastLevel": 101142,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 51,
                  "championLevel": 7,
                  "championPoints": 97088,
                  "lastPlayTime": 1689608208000,
                  "championPointsSinceLastLevel": 75488,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 18,
                  "championLevel": 7,
                  "championPoints": 96320,
                  "lastPlayTime": 1691506989000,
                  "championPointsSinceLastLevel": 74720,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 67,
                  "championLevel": 7,
                  "championPoints": 94173,
                  "lastPlayTime": 1689000385000,
                  "championPointsSinceLastLevel": 72573,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 22,
                  "championLevel": 7,
                  "championPoints": 90936,
                  "lastPlayTime": 1688918731000,
                  "championPointsSinceLastLevel": 69336,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 222,
                  "championLevel": 7,
                  "championPoints": 90793,
                  "lastPlayTime": 1689082443000,
                  "championPointsSinceLastLevel": 69193,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 110,
                  "championLevel": 7,
                  "championPoints": 88346,
                  "lastPlayTime": 1690042161000,
                  "championPointsSinceLastLevel": 66746,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 412,
                  "championLevel": 7,
                  "championPoints": 82983,
                  "lastPlayTime": 1690641011000,
                  "championPointsSinceLastLevel": 61383,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 122,
                  "championLevel": 7,
                  "championPoints": 75472,
                  "lastPlayTime": 1689786977000,
                  "championPointsSinceLastLevel": 53872,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 53,
                  "championLevel": 7,
                  "championPoints": 60158,
                  "lastPlayTime": 1689442885000,
                  "championPointsSinceLastLevel": 38558,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 202,
                  "championLevel": 7,
                  "championPoints": 59348,
                  "lastPlayTime": 1689348369000,
                  "championPointsSinceLastLevel": 37748,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 25,
                  "championLevel": 6,
                  "championPoints": 51322,
                  "lastPlayTime": 1690902513000,
                  "championPointsSinceLastLevel": 29722,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 2,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 266,
                  "championLevel": 7,
                  "championPoints": 48605,
                  "lastPlayTime": 1684856659000,
                  "championPointsSinceLastLevel": 27005,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 236,
                  "championLevel": 6,
                  "championPoints": 46571,
                  "lastPlayTime": 1691338284000,
                  "championPointsSinceLastLevel": 24971,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 103,
                  "championLevel": 6,
                  "championPoints": 45223,
                  "lastPlayTime": 1690212546000,
                  "championPointsSinceLastLevel": 23623,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 15,
                  "championLevel": 7,
                  "championPoints": 44701,
                  "lastPlayTime": 1689513492000,
                  "championPointsSinceLastLevel": 23101,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 13,
                  "championLevel": 6,
                  "championPoints": 42506,
                  "lastPlayTime": 1691249495000,
                  "championPointsSinceLastLevel": 20906,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 2,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 145,
                  "championLevel": 6,
                  "championPoints": 41757,
                  "lastPlayTime": 1690818614000,
                  "championPointsSinceLastLevel": 20157,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 134,
                  "championLevel": 6,
                  "championPoints": 41618,
                  "lastPlayTime": 1691335676000,
                  "championPointsSinceLastLevel": 20018,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 4,
                  "championLevel": 5,
                  "championPoints": 40844,
                  "lastPlayTime": 1685317225000,
                  "championPointsSinceLastLevel": 19244,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 126,
                  "championLevel": 5,
                  "championPoints": 40761,
                  "lastPlayTime": 1689444659000,
                  "championPointsSinceLastLevel": 19161,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 63,
                  "championLevel": 6,
                  "championPoints": 40530,
                  "lastPlayTime": 1689785511000,
                  "championPointsSinceLastLevel": 18930,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 555,
                  "championLevel": 7,
                  "championPoints": 39917,
                  "lastPlayTime": 1690293747000,
                  "championPointsSinceLastLevel": 18317,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 238,
                  "championLevel": 5,
                  "championPoints": 38960,
                  "lastPlayTime": 1678136900000,
                  "championPointsSinceLastLevel": 17360,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 45,
                  "championLevel": 5,
                  "championPoints": 38879,
                  "lastPlayTime": 1691253154000,
                  "championPointsSinceLastLevel": 17279,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 62,
                  "championLevel": 6,
                  "championPoints": 37902,
                  "lastPlayTime": 1681658111000,
                  "championPointsSinceLastLevel": 16302,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 21,
                  "championLevel": 6,
                  "championPoints": 37476,
                  "lastPlayTime": 1689514904000,
                  "championPointsSinceLastLevel": 15876,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 76,
                  "championLevel": 5,
                  "championPoints": 36303,
                  "lastPlayTime": 1688732663000,
                  "championPointsSinceLastLevel": 14703,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 75,
                  "championLevel": 6,
                  "championPoints": 36147,
                  "lastPlayTime": 1673800966000,
                  "championPointsSinceLastLevel": 14547,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 24,
                  "championLevel": 6,
                  "championPoints": 36069,
                  "lastPlayTime": 1684778035000,
                  "championPointsSinceLastLevel": 14469,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 54,
                  "championLevel": 5,
                  "championPoints": 35229,
                  "lastPlayTime": 1690209725000,
                  "championPointsSinceLastLevel": 13629,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 101,
                  "championLevel": 6,
                  "championPoints": 34924,
                  "lastPlayTime": 1689008147000,
                  "championPointsSinceLastLevel": 13324,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 86,
                  "championLevel": 6,
                  "championPoints": 34904,
                  "lastPlayTime": 1689523293000,
                  "championPointsSinceLastLevel": 13304,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 79,
                  "championLevel": 5,
                  "championPoints": 34573,
                  "lastPlayTime": 1691163642000,
                  "championPointsSinceLastLevel": 12973,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 350,
                  "championLevel": 5,
                  "championPoints": 34306,
                  "lastPlayTime": 1680189325000,
                  "championPointsSinceLastLevel": 12706,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 245,
                  "championLevel": 6,
                  "championPoints": 34226,
                  "lastPlayTime": 1690816154000,
                  "championPointsSinceLastLevel": 12626,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 80,
                  "championLevel": 6,
                  "championPoints": 32518,
                  "lastPlayTime": 1691514387000,
                  "championPointsSinceLastLevel": 10918,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": true,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 23,
                  "championLevel": 6,
                  "championPoints": 32074,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 10474,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 119,
                  "championLevel": 5,
                  "championPoints": 30366,
                  "lastPlayTime": 1678037937000,
                  "championPointsSinceLastLevel": 8766,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 114,
                  "championLevel": 6,
                  "championPoints": 30333,
                  "lastPlayTime": 1680445720000,
                  "championPointsSinceLastLevel": 8733,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 84,
                  "championLevel": 6,
                  "championPoints": 30264,
                  "lastPlayTime": 1685028036000,
                  "championPointsSinceLastLevel": 8664,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 85,
                  "championLevel": 5,
                  "championPoints": 29949,
                  "lastPlayTime": 1688924887000,
                  "championPointsSinceLastLevel": 8349,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 115,
                  "championLevel": 5,
                  "championPoints": 29296,
                  "lastPlayTime": 1690988166000,
                  "championPointsSinceLastLevel": 7696,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 5,
                  "championLevel": 6,
                  "championPoints": 28940,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 7340,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 111,
                  "championLevel": 5,
                  "championPoints": 28255,
                  "lastPlayTime": 1690727729000,
                  "championPointsSinceLastLevel": 6655,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 7,
                  "championLevel": 5,
                  "championPoints": 28198,
                  "lastPlayTime": 1691079158000,
                  "championPointsSinceLastLevel": 6598,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 235,
                  "championLevel": 5,
                  "championPoints": 28168,
                  "lastPlayTime": 1688923143000,
                  "championPointsSinceLastLevel": 6568,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 14,
                  "championLevel": 5,
                  "championPoints": 27820,
                  "lastPlayTime": 1691511603000,
                  "championPointsSinceLastLevel": 6220,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 37,
                  "championLevel": 5,
                  "championPoints": 27474,
                  "lastPlayTime": 1677177072000,
                  "championPointsSinceLastLevel": 5874,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 117,
                  "championLevel": 5,
                  "championPoints": 27418,
                  "lastPlayTime": 1683905535000,
                  "championPointsSinceLastLevel": 5818,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 96,
                  "championLevel": 5,
                  "championPoints": 27187,
                  "lastPlayTime": 1683908659000,
                  "championPointsSinceLastLevel": 5587,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 147,
                  "championLevel": 5,
                  "championPoints": 26716,
                  "lastPlayTime": 1685719933000,
                  "championPointsSinceLastLevel": 5116,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 61,
                  "championLevel": 5,
                  "championPoints": 26156,
                  "lastPlayTime": 1691160762000,
                  "championPointsSinceLastLevel": 4556,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 91,
                  "championLevel": 5,
                  "championPoints": 25876,
                  "lastPlayTime": 1691166675000,
                  "championPointsSinceLastLevel": 4276,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 41,
                  "championLevel": 5,
                  "championPoints": 25750,
                  "lastPlayTime": 1688747968000,
                  "championPointsSinceLastLevel": 4150,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 68,
                  "championLevel": 5,
                  "championPoints": 24807,
                  "lastPlayTime": 1684942628000,
                  "championPointsSinceLastLevel": 3207,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 267,
                  "championLevel": 5,
                  "championPoints": 24615,
                  "lastPlayTime": 1676305843000,
                  "championPointsSinceLastLevel": 3015,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 1,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 429,
                  "championLevel": 5,
                  "championPoints": 24356,
                  "lastPlayTime": 1677953739000,
                  "championPointsSinceLastLevel": 2756,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 16,
                  "championLevel": 5,
                  "championPoints": 24209,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 2609,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 59,
                  "championLevel": 5,
                  "championPoints": 23317,
                  "lastPlayTime": 1688920011000,
                  "championPointsSinceLastLevel": 1717,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 150,
                  "championLevel": 5,
                  "championPoints": 23038,
                  "lastPlayTime": 1675277180000,
                  "championPointsSinceLastLevel": 1438,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 498,
                  "championLevel": 5,
                  "championPoints": 22924,
                  "lastPlayTime": 1689181895000,
                  "championPointsSinceLastLevel": 1324,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 112,
                  "championLevel": 5,
                  "championPoints": 22568,
                  "lastPlayTime": 1685373704000,
                  "championPointsSinceLastLevel": 968,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 107,
                  "championLevel": 5,
                  "championPoints": 22321,
                  "lastPlayTime": 1681494157000,
                  "championPointsSinceLastLevel": 721,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 40,
                  "championLevel": 5,
                  "championPoints": 22196,
                  "lastPlayTime": 1676310864000,
                  "championPointsSinceLastLevel": 596,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 17,
                  "championLevel": 5,
                  "championPoints": 22135,
                  "lastPlayTime": 1686245032000,
                  "championPointsSinceLastLevel": 535,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 8,
                  "championLevel": 5,
                  "championPoints": 21931,
                  "lastPlayTime": 1683557015000,
                  "championPointsSinceLastLevel": 331,
                  "championPointsUntilNextLevel": 0,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 105,
                  "championLevel": 4,
                  "championPoints": 21299,
                  "lastPlayTime": 1691341081000,
                  "championPointsSinceLastLevel": 8699,
                  "championPointsUntilNextLevel": 301,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 2,
                  "championLevel": 4,
                  "championPoints": 20870,
                  "lastPlayTime": 1684770137000,
                  "championPointsSinceLastLevel": 8270,
                  "championPointsUntilNextLevel": 730,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 34,
                  "championLevel": 4,
                  "championPoints": 20786,
                  "lastPlayTime": 1682965568000,
                  "championPointsSinceLastLevel": 8186,
                  "championPointsUntilNextLevel": 814,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 161,
                  "championLevel": 4,
                  "championPoints": 20071,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 7471,
                  "championPointsUntilNextLevel": 1529,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 875,
                  "championLevel": 4,
                  "championPoints": 19937,
                  "lastPlayTime": 1680361485000,
                  "championPointsSinceLastLevel": 7337,
                  "championPointsUntilNextLevel": 1663,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 29,
                  "championLevel": 4,
                  "championPoints": 19258,
                  "lastPlayTime": 1689581546000,
                  "championPointsSinceLastLevel": 6658,
                  "championPointsUntilNextLevel": 2342,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 3,
                  "championLevel": 4,
                  "championPoints": 19023,
                  "lastPlayTime": 1690039522000,
                  "championPointsSinceLastLevel": 6423,
                  "championPointsUntilNextLevel": 2577,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 26,
                  "championLevel": 4,
                  "championPoints": 18632,
                  "lastPlayTime": 1685108285000,
                  "championPointsSinceLastLevel": 6032,
                  "championPointsUntilNextLevel": 2968,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 164,
                  "championLevel": 4,
                  "championPoints": 18246,
                  "lastPlayTime": 1674830444000,
                  "championPointsSinceLastLevel": 5646,
                  "championPointsUntilNextLevel": 3354,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 104,
                  "championLevel": 4,
                  "championPoints": 18210,
                  "lastPlayTime": 1689520600000,
                  "championPointsSinceLastLevel": 5610,
                  "championPointsUntilNextLevel": 3390,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 39,
                  "championLevel": 4,
                  "championPoints": 18093,
                  "lastPlayTime": 1675444797000,
                  "championPointsSinceLastLevel": 5493,
                  "championPointsUntilNextLevel": 3507,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 42,
                  "championLevel": 4,
                  "championPoints": 16380,
                  "lastPlayTime": 1685638945000,
                  "championPointsSinceLastLevel": 3780,
                  "championPointsUntilNextLevel": 5220,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 90,
                  "championLevel": 4,
                  "championPoints": 16169,
                  "lastPlayTime": 1689579262000,
                  "championPointsSinceLastLevel": 3569,
                  "championPointsUntilNextLevel": 5431,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 268,
                  "championLevel": 4,
                  "championPoints": 15989,
                  "lastPlayTime": 1689580477000,
                  "championPointsSinceLastLevel": 3389,
                  "championPointsUntilNextLevel": 5611,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 1,
                  "championLevel": 4,
                  "championPoints": 15859,
                  "lastPlayTime": 1682624728000,
                  "championPointsSinceLastLevel": 3259,
                  "championPointsUntilNextLevel": 5741,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 43,
                  "championLevel": 4,
                  "championPoints": 15844,
                  "lastPlayTime": 1684854482000,
                  "championPointsSinceLastLevel": 3244,
                  "championPointsUntilNextLevel": 5756,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 74,
                  "championLevel": 4,
                  "championPoints": 14111,
                  "lastPlayTime": 1685200816000,
                  "championPointsSinceLastLevel": 1511,
                  "championPointsUntilNextLevel": 7489,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 57,
                  "championLevel": 4,
                  "championPoints": 14105,
                  "lastPlayTime": 1677516692000,
                  "championPointsSinceLastLevel": 1505,
                  "championPointsUntilNextLevel": 7495,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 10,
                  "championLevel": 4,
                  "championPoints": 14070,
                  "lastPlayTime": 1688749924000,
                  "championPointsSinceLastLevel": 1470,
                  "championPointsUntilNextLevel": 7530,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 69,
                  "championLevel": 4,
                  "championPoints": 13467,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 867,
                  "championPointsUntilNextLevel": 8133,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 35,
                  "championLevel": 4,
                  "championPoints": 13431,
                  "lastPlayTime": 1688145163000,
                  "championPointsSinceLastLevel": 831,
                  "championPointsUntilNextLevel": 8169,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 142,
                  "championLevel": 4,
                  "championPoints": 13092,
                  "lastPlayTime": 1683558760000,
                  "championPointsSinceLastLevel": 492,
                  "championPointsUntilNextLevel": 8508,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 27,
                  "championLevel": 4,
                  "championPoints": 12866,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 266,
                  "championPointsUntilNextLevel": 8734,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 497,
                  "championLevel": 4,
                  "championPoints": 12837,
                  "lastPlayTime": 1690823628000,
                  "championPointsSinceLastLevel": 237,
                  "championPointsUntilNextLevel": 8763,
                  "chestGranted": true,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 141,
                  "championLevel": 3,
                  "championPoints": 12287,
                  "lastPlayTime": 1689519500000,
                  "championPointsSinceLastLevel": 6287,
                  "championPointsUntilNextLevel": 313,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 55,
                  "championLevel": 3,
                  "championPoints": 12152,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 6152,
                  "championPointsUntilNextLevel": 448,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 163,
                  "championLevel": 3,
                  "championPoints": 11935,
                  "lastPlayTime": 1689272180000,
                  "championPointsSinceLastLevel": 5935,
                  "championPointsUntilNextLevel": 665,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 89,
                  "championLevel": 3,
                  "championPoints": 11829,
                  "lastPlayTime": 1675548173000,
                  "championPointsSinceLastLevel": 5829,
                  "championPointsUntilNextLevel": 771,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 50,
                  "championLevel": 3,
                  "championPoints": 11811,
                  "lastPlayTime": 1690560222000,
                  "championPointsSinceLastLevel": 5811,
                  "championPointsUntilNextLevel": 789,
                  "chestGranted": true,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 20,
                  "championLevel": 3,
                  "championPoints": 11511,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 5511,
                  "championPointsUntilNextLevel": 1089,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 517,
                  "championLevel": 3,
                  "championPoints": 11259,
                  "lastPlayTime": 1685636193000,
                  "championPointsSinceLastLevel": 5259,
                  "championPointsUntilNextLevel": 1341,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 127,
                  "championLevel": 3,
                  "championPoints": 10849,
                  "lastPlayTime": 1682268466000,
                  "championPointsSinceLastLevel": 4849,
                  "championPointsUntilNextLevel": 1751,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 6,
                  "championLevel": 3,
                  "championPoints": 10828,
                  "lastPlayTime": 1675878756000,
                  "championPointsSinceLastLevel": 4828,
                  "championPointsUntilNextLevel": 1772,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 360,
                  "championLevel": 3,
                  "championPoints": 10472,
                  "lastPlayTime": 1682102564000,
                  "championPointsSinceLastLevel": 4472,
                  "championPointsUntilNextLevel": 2128,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 78,
                  "championLevel": 3,
                  "championPoints": 9936,
                  "lastPlayTime": 1679939443000,
                  "championPointsSinceLastLevel": 3936,
                  "championPointsUntilNextLevel": 2664,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 518,
                  "championLevel": 3,
                  "championPoints": 9743,
                  "lastPlayTime": 1685810973000,
                  "championPointsSinceLastLevel": 3743,
                  "championPointsUntilNextLevel": 2857,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 82,
                  "championLevel": 3,
                  "championPoints": 9726,
                  "lastPlayTime": 1689512341000,
                  "championPointsSinceLastLevel": 3726,
                  "championPointsUntilNextLevel": 2874,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 12,
                  "championLevel": 3,
                  "championPoints": 9495,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3495,
                  "championPointsUntilNextLevel": 3105,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 777,
                  "championLevel": 3,
                  "championPoints": 9415,
                  "lastPlayTime": 1691509335000,
                  "championPointsSinceLastLevel": 3415,
                  "championPointsUntilNextLevel": 3185,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 60,
                  "championLevel": 3,
                  "championPoints": 9141,
                  "lastPlayTime": 1681650857000,
                  "championPointsSinceLastLevel": 3141,
                  "championPointsUntilNextLevel": 3459,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 106,
                  "championLevel": 3,
                  "championPoints": 9006,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3006,
                  "championPointsUntilNextLevel": 3594,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 203,
                  "championLevel": 3,
                  "championPoints": 8890,
                  "lastPlayTime": 1689429213000,
                  "championPointsSinceLastLevel": 2890,
                  "championPointsUntilNextLevel": 3710,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 102,
                  "championLevel": 3,
                  "championPoints": 8725,
                  "lastPlayTime": 1689600807000,
                  "championPointsSinceLastLevel": 2725,
                  "championPointsUntilNextLevel": 3875,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 876,
                  "championLevel": 3,
                  "championPoints": 8613,
                  "lastPlayTime": 1673807173000,
                  "championPointsSinceLastLevel": 2613,
                  "championPointsUntilNextLevel": 3987,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 19,
                  "championLevel": 3,
                  "championPoints": 8483,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 2483,
                  "championPointsUntilNextLevel": 4117,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 223,
                  "championLevel": 3,
                  "championPoints": 8115,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 2115,
                  "championPointsUntilNextLevel": 4485,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 131,
                  "championLevel": 3,
                  "championPoints": 8100,
                  "lastPlayTime": 1689784138000,
                  "championPointsSinceLastLevel": 2100,
                  "championPointsUntilNextLevel": 4500,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 58,
                  "championLevel": 3,
                  "championPoints": 8000,
                  "lastPlayTime": 1679156178000,
                  "championPointsSinceLastLevel": 2000,
                  "championPointsUntilNextLevel": 4600,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 154,
                  "championLevel": 3,
                  "championPoints": 7893,
                  "lastPlayTime": 1689516157000,
                  "championPointsSinceLastLevel": 1893,
                  "championPointsUntilNextLevel": 4707,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 136,
                  "championLevel": 3,
                  "championPoints": 7818,
                  "lastPlayTime": 1690386451000,
                  "championPointsSinceLastLevel": 1818,
                  "championPointsUntilNextLevel": 4782,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 56,
                  "championLevel": 3,
                  "championPoints": 7745,
                  "lastPlayTime": 1673969673000,
                  "championPointsSinceLastLevel": 1745,
                  "championPointsUntilNextLevel": 4855,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 427,
                  "championLevel": 3,
                  "championPoints": 7665,
                  "lastPlayTime": 1691516676000,
                  "championPointsSinceLastLevel": 1665,
                  "championPointsUntilNextLevel": 4935,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 234,
                  "championLevel": 3,
                  "championPoints": 7637,
                  "lastPlayTime": 1688734387000,
                  "championPointsSinceLastLevel": 1637,
                  "championPointsUntilNextLevel": 4963,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 9,
                  "championLevel": 3,
                  "championPoints": 7475,
                  "lastPlayTime": 1673974101000,
                  "championPointsSinceLastLevel": 1475,
                  "championPointsUntilNextLevel": 5125,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 98,
                  "championLevel": 3,
                  "championPoints": 7339,
                  "lastPlayTime": 1675352729000,
                  "championPointsSinceLastLevel": 1339,
                  "championPointsUntilNextLevel": 5261,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 92,
                  "championLevel": 3,
                  "championPoints": 7313,
                  "lastPlayTime": 1673639280000,
                  "championPointsSinceLastLevel": 1313,
                  "championPointsUntilNextLevel": 5287,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 32,
                  "championLevel": 3,
                  "championPoints": 7291,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 1291,
                  "championPointsUntilNextLevel": 5309,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 113,
                  "championLevel": 3,
                  "championPoints": 7181,
                  "lastPlayTime": 1683129415000,
                  "championPointsSinceLastLevel": 1181,
                  "championPointsUntilNextLevel": 5419,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 133,
                  "championLevel": 3,
                  "championPoints": 7084,
                  "lastPlayTime": 1689180218000,
                  "championPointsSinceLastLevel": 1084,
                  "championPointsUntilNextLevel": 5516,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 31,
                  "championLevel": 3,
                  "championPoints": 6988,
                  "lastPlayTime": 1674487529000,
                  "championPointsSinceLastLevel": 988,
                  "championPointsUntilNextLevel": 5612,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 432,
                  "championLevel": 3,
                  "championPoints": 6972,
                  "lastPlayTime": 1689094095000,
                  "championPointsSinceLastLevel": 972,
                  "championPointsUntilNextLevel": 5628,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 44,
                  "championLevel": 3,
                  "championPoints": 6937,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 937,
                  "championPointsUntilNextLevel": 5663,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 143,
                  "championLevel": 3,
                  "championPoints": 6510,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 510,
                  "championPointsUntilNextLevel": 6090,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 36,
                  "championLevel": 3,
                  "championPoints": 6384,
                  "lastPlayTime": 1674829326000,
                  "championPointsSinceLastLevel": 384,
                  "championPointsUntilNextLevel": 6216,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 254,
                  "championLevel": 2,
                  "championPoints": 5697,
                  "lastPlayTime": 1685203384000,
                  "championPointsSinceLastLevel": 3897,
                  "championPointsUntilNextLevel": 303,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 38,
                  "championLevel": 2,
                  "championPoints": 5528,
                  "lastPlayTime": 1673111955000,
                  "championPointsSinceLastLevel": 3728,
                  "championPointsUntilNextLevel": 472,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 120,
                  "championLevel": 2,
                  "championPoints": 5473,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3673,
                  "championPointsUntilNextLevel": 527,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 516,
                  "championLevel": 2,
                  "championPoints": 5440,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3640,
                  "championPointsUntilNextLevel": 560,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 201,
                  "championLevel": 2,
                  "championPoints": 5429,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3629,
                  "championPointsUntilNextLevel": 571,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 30,
                  "championLevel": 2,
                  "championPoints": 5032,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3232,
                  "championPointsUntilNextLevel": 968,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 48,
                  "championLevel": 2,
                  "championPoints": 5024,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 3224,
                  "championPointsUntilNextLevel": 976,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 420,
                  "championLevel": 2,
                  "championPoints": 4847,
                  "lastPlayTime": 1689526350000,
                  "championPointsSinceLastLevel": 3047,
                  "championPointsUntilNextLevel": 1153,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 421,
                  "championLevel": 2,
                  "championPoints": 4512,
                  "lastPlayTime": 1689527861000,
                  "championPointsSinceLastLevel": 2712,
                  "championPointsUntilNextLevel": 1488,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 33,
                  "championLevel": 2,
                  "championPoints": 4231,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 2431,
                  "championPointsUntilNextLevel": 1769,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 240,
                  "championLevel": 2,
                  "championPoints": 3844,
                  "lastPlayTime": 1679236595000,
                  "championPointsSinceLastLevel": 2044,
                  "championPointsUntilNextLevel": 2156,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 523,
                  "championLevel": 2,
                  "championPoints": 3010,
                  "lastPlayTime": 1689508987000,
                  "championPointsSinceLastLevel": 1210,
                  "championPointsUntilNextLevel": 2990,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 888,
                  "championLevel": 2,
                  "championPoints": 2824,
                  "lastPlayTime": 1679403999000,
                  "championPointsSinceLastLevel": 1024,
                  "championPointsUntilNextLevel": 3176,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 77,
                  "championLevel": 2,
                  "championPoints": 2645,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 845,
                  "championPointsUntilNextLevel": 3355,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 83,
                  "championLevel": 2,
                  "championPoints": 2559,
                  "lastPlayTime": 1673808800000,
                  "championPointsSinceLastLevel": 759,
                  "championPointsUntilNextLevel": 3441,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 897,
                  "championLevel": 2,
                  "championPoints": 2468,
                  "lastPlayTime": 1683561739000,
                  "championPointsSinceLastLevel": 668,
                  "championPointsUntilNextLevel": 3532,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 221,
                  "championLevel": 2,
                  "championPoints": 2416,
                  "lastPlayTime": 1689511119000,
                  "championPointsSinceLastLevel": 616,
                  "championPointsUntilNextLevel": 3584,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 711,
                  "championLevel": 2,
                  "championPoints": 2132,
                  "lastPlayTime": 1690814760000,
                  "championPointsSinceLastLevel": 332,
                  "championPointsUntilNextLevel": 3868,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 246,
                  "championLevel": 2,
                  "championPoints": 1990,
                  "lastPlayTime": 1686675393000,
                  "championPointsSinceLastLevel": 190,
                  "championPointsUntilNextLevel": 4010,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 166,
                  "championLevel": 1,
                  "championPoints": 1115,
                  "lastPlayTime": 1688921483000,
                  "championPointsSinceLastLevel": 1115,
                  "championPointsUntilNextLevel": 685,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 72,
                  "championLevel": 1,
                  "championPoints": 1005,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 1005,
                  "championPointsUntilNextLevel": 795,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 28,
                  "championLevel": 1,
                  "championPoints": 727,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 727,
                  "championPointsUntilNextLevel": 1073,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 887,
                  "championLevel": 1,
                  "championPoints": 467,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 467,
                  "championPointsUntilNextLevel": 1333,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              },
              {
                  "puuid": "BAL9b14pQJ-1CHavG9_OxgrBNJuueZw7bttYUJVM-mUll3_9SwD8FO-LOodmEaoE76ViqpQLTnQleA",
                  "championId": 526,
                  "championLevel": 1,
                  "championPoints": 374,
                  "lastPlayTime": 1672940000000,
                  "championPointsSinceLastLevel": 374,
                  "championPointsUntilNextLevel": 1426,
                  "chestGranted": false,
                  "tokensEarned": 0,
                  "summonerId": "yX-TkkDPsKfh2doN5bkW1mH3sRxSJpkKWYr57DZR-n5L50wDEhLMqc07NA"
              }
          ]}
            shouldInitiallyExpand={(level) => true}
            style={defaultStyles}
          />
        </div>
      </section>
    </main>
  );
}
